development:
  adapter: postgresql
  encoding: unicode
  database: quotenote_development
  pool: 5
  username: quotenote
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: quotenote_test
  pool: 5
  username: quotenote
  password: password
